/*
 * This source file was generated by the Gradle 'init' task
 */
package com.mrap.androidutil.sparsearray;

public class Sandbox {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Sandbox().getGreeting());
    }
}
