/*
 * This source file was generated by the Gradle 'init' task
 */
package com.mrap.androidutil.sparsearray;

import org.junit.jupiter.api.Test;

class SandboxTest {
    @Test void appHasAGreeting() {
        Sandbox classUnderTest = new Sandbox();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
